# Generated by Django 4.2.6 on 2023-11-06 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_registration_name_alter_registration_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_group', models.CharField(max_length=30)),
                ('item_desc', models.CharField(max_length=30)),
                ('stock_qty', models.IntegerField(max_length=20)),
                ('item_rate', models.IntegerField(max_length=20)),
                ('item_date', models.DateField()),
            ],
        ),
    ]
