# Generated by Django 4.2.6 on 2023-11-06 06:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_item'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Item',
            new_name='ItemInsert',
        ),
    ]
