# Generated by Django 4.2.6 on 2023-11-06 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_rename_item_iteminsert'),
    ]

    operations = [
        migrations.AddField(
            model_name='iteminsert',
            name='image',
            field=models.ImageField(default='', upload_to='seller/images'),
        ),
        migrations.AlterField(
            model_name='iteminsert',
            name='item_rate',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='iteminsert',
            name='stock_qty',
            field=models.IntegerField(),
        ),
    ]
