# Generated by Django 4.2.6 on 2023-11-06 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_iteminsert_image_alter_iteminsert_item_rate_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='iteminsert',
            name='image',
        ),
    ]
