# Generated by Django 4.2.6 on 2023-11-07 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_remove_iteminsert_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='iteminsert',
            name='image',
            field=models.ImageField(default='', upload_to='seller/images'),
        ),
    ]
