# Generated by Django 4.2.6 on 2023-12-06 15:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_contact'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='Mobile',
            new_name='mobile',
        ),
    ]
