# Generated by Django 4.2.6 on 2023-12-16 07:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_checkout'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Checkout',
        ),
    ]
