# Generated by Django 4.2.6 on 2023-12-20 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_orderupdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='iteminsert',
            name='item_rate',
            field=models.IntegerField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='iteminsert',
            name='stock_qty',
            field=models.IntegerField(max_length=30),
        ),
    ]
