# Generated by Django 4.2.6 on 2023-12-27 03:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_alter_blogpost_thumbnail'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogpost',
            old_name='tilte',
            new_name='title',
        ),
    ]
