# Generated by Django 4.2.6 on 2024-01-08 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_rename_tilte_blogpost_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkout',
            name='amount',
            field=models.IntegerField(default=0, max_length=100),
        ),
    ]
