# Generated by Django 4.2.6 on 2024-01-08 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0018_checkout_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkout',
            name='amount',
            field=models.IntegerField(default=0),
        ),
    ]
